const livros = [
    {
        id: 1,
        titulo: "O Hobbit",
        autor: "J.R.R. Tolkien",
        isbn: 9788533302184,
        categoria: "Fantasia",
        anoPublicacao: 1937,
        disponivel: true,
        editora: "HarperCollins Brasil",
    },
    {
        id: 2,
        titulo: "1984",
        autor: "George Orwell",
        isbn: 9788535914847,
        categoria: "Ficção Distópica",
        anoPublicacao: 1949,
        disponivel: false,
        editora: "Companhia das Letras",
    },
    {
        id: 3,
        titulo: "Orgulho e Preconceito",
        autor: "Jane Austen",
        isbn: 9788580400250,
        categoria: "Romance Clássico",
        anoPublicacao: 1813,
        disponivel: true,
        editora: "Martin Claret",
    },
    {
        id: 4,
        titulo: "A Metamorfose",
        autor: "Franz Kafka",
        isbn: 9788572322437,
        categoria: "Ficção Clássica",
        anoPublicacao: 1915,
        disponivel: true,
        editora: "L&PM Editores",
    },
    {
        id: 5,
        titulo: "Cem Anos de Solidão",
        autor: "Gabriel García Márquez",
        isbn: 9788501028444,
        categoria: "Realismo Mágico",
        anoPublicacao: 1967,
        disponivel: false,
        editora: "Record",
    },
    {
        id: 6,
        titulo: "Crime e Castigo",
        autor: "Fiódor Dostoiévski",
        isbn: 9788573261759,
        categoria: "Ficção Filosófica",
        anoPublicacao: 1866,
        disponivel: true,
        editora: "Editora 34",
    },
    {
        id: 7,
        titulo: "O Pequeno Príncipe",
        autor: "Antoine de Saint-Exupéry",
        isbn: 9788595084428,
        categoria: "Literatura Infantil",
        anoPublicacao: 1943,
        disponivel: true,
        editora: "Agir",
    },
    {
        id: 8,
        titulo: "A Revolução dos Bichos",
        autor: "George Orwell",
        isbn: 9788535909555,
        categoria: "Sátira Política",
        anoPublicacao: 1945,
        disponivel: true,
        editora: "Companhia das Letras",
    },
    {
        id: 9,
        titulo: "Dom Quixote",
        autor: "Miguel de Cervantes",
        isbn: 9788572322611,
        categoria: "Romance de Aventura",
        anoPublicacao: 1605,
        disponivel: true,
        editora: "Penguin-Companhia",
    },
    {
        id: 10,
        titulo: "Harry Potter e a Pedra Filosofal",
        autor: "J.K. Rowling",
        isbn: 9788532511010,
        categoria: "Fantasia Infanto-Juvenil",
        anoPublicacao: 1997,
        disponivel: true,
        editora: "Rocco",
    },
];

export default { livros }