const livros = [
    {
        id: 1,
        titulo: "O Hobbit",
        autor: "J.R.R. Tolkien",
        isbn: "978-85-333-0218-4",
        categoria: "Fantasia",
        anoPublicacao: 1937,
        disponivel: true,
        editora: "HarperCollins Brasil",
    },
    {
        id: 2,
        titulo: "1984",
        autor: "George Orwell",
        isbn: "978-85-359-1484-9",
        categoria: "Ficção Distópica",
        anoPublicacao: 1949,
        disponivel: false,
        editora: "Companhia das Letras",
    },
    {
        id: 3,
        titulo: "Orgulho e Preconceito",
        autor: "Jane Austen",
        isbn: "978-85-8040-025-0",
        categoria: "Romance Clássico",
        anoPublicacao: 1813,
        disponivel: true,
        editora: "Martin Claret",
    },
    {
        id: 4,
        titulo: "A Metamorfose",
        autor: "Franz Kafka",
        isbn: "978-85-7232-243-7",
        categoria: "Ficção Clássica",
        anoPublicacao: 1915,
        disponivel: true,
        editora: "L&PM Editores",
    },
    {
        id: 5,
        titulo: "Cem Anos de Solidão",
        autor: "Gabriel García Márquez",
        isbn: "978-85-01-02844-4",
        categoria: "Realismo Mágico",
        anoPublicacao: 1967,
        disponivel: false,
        editora: "Record",
    },
    {
        id: 6,
        titulo: "Crime e Castigo",
        autor: "Fiódor Dostoiévski",
        isbn: "978-85-7326-175-9",
        categoria: "Ficção Filosófica",
        anoPublicacao: 1866,
        disponivel: true,
        editora: "Editora 34",
    },
    {
        id: 7,
        titulo: "O Pequeno Príncipe",
        autor: "Antoine de Saint-Exupéry",
        isbn: "978-85-950-8442-8",
        categoria: "Literatura Infantil",
        anoPublicacao: 1943,
        disponivel: true,
        editora: "Agir",
    },
    {
        id: 8,
        titulo: "A Revolução dos Bichos",
        autor: "George Orwell",
        isbn: "978-85-359-0955-5",
        categoria: "Sátira Política",
        anoPublicacao: 1945,
        disponivel: true,
        editora: "Companhia das Letras",
    },
    {
        id: 9,
        titulo: "Dom Quixote",
        autor: "Miguel de Cervantes",
        isbn: "978-85-7232-261-1",
        categoria: "Romance de Aventura",
        anoPublicacao: 1605,
        disponivel: true,
        editora: "Penguin-Companhia",
    },
    {
        id: 10,
        titulo: "Harry Potter e a Pedra Filosofal",
        autor: "J.K. Rowling",
        isbn: "978-85-325-1101-0",
        categoria: "Fantasia Infanto-Juvenil",
        anoPublicacao: 1997,
        disponivel: true,
        editora: "Rocco",
    },
];

export default { livros };